import { redux } from '@simrs/common';

const { types, createRequestType, createType } = redux;

const { REQUEST, SUCCESS, FAILURE } = types;
const GET_PASIEN = createRequestType('GET_PASIEN');
const GET_KUNJUNGAN = createRequestType('GET_KUNJUNGAN');
const GET_KUNJUNGAN_DETAIL = createRequestType('GET_KUNJUNGAN_DETAIL');
const POPULATE_FORM = createRequestType('POPULATE_FORM');
const SAVE = createRequestType('SAVE_DATA');
const DELETE = createRequestType('DELETE_DATA');
const GET_ADMINISTRASI_KONSUL = createRequestType('GET_ADMINISTRASI_KONSUL');
const GET_KUNJUNGAN_UNIT_DETAIL = createRequestType(
  'GET_KUNJUNGAN_UNIT_DETAIL'
);

export default {
  SAVE_REQUEST: SAVE[REQUEST],
  SAVE_SUCCESS: SAVE[SUCCESS],
  SAVE_FAILURE: SAVE[FAILURE],

  DELETE_REQUEST: DELETE[REQUEST],
  DELETE_SUCCESS: DELETE[SUCCESS],
  DELETE_FAILURE: DELETE[FAILURE],

  POPULATE_FORM_REQUEST: POPULATE_FORM[REQUEST],
  POPULATE_FORM_SUCCESS: POPULATE_FORM[SUCCESS],
  POPULATE_FORM_FAILURE: POPULATE_FORM[FAILURE],

  GET_PASIEN_REQUEST: GET_PASIEN[REQUEST],
  GET_PASIEN_SUCCESS: GET_PASIEN[SUCCESS],
  GET_PASIEN_FAILURE: GET_PASIEN[FAILURE],

  GET_KUNJUNGAN_REQUEST: GET_KUNJUNGAN[REQUEST],
  GET_KUNJUNGAN_SUCCESS: GET_KUNJUNGAN[SUCCESS],
  GET_KUNJUNGAN_FAILURE: GET_KUNJUNGAN[FAILURE],

  GET_ADMINISTRASI_KONSUL_REQUEST: GET_ADMINISTRASI_KONSUL[REQUEST],
  GET_ADMINISTRASI_KONSUL_SUCCESS: GET_ADMINISTRASI_KONSUL[SUCCESS],
  GET_ADMINISTRASI_KONSUL_FAILURE: GET_ADMINISTRASI_KONSUL[FAILURE],

  GET_KUNJUNGAN_DETAIL_REQUEST: GET_KUNJUNGAN_DETAIL[REQUEST],
  GET_KUNJUNGAN_DETAIL_SUCCESS: GET_KUNJUNGAN_DETAIL[SUCCESS],
  GET_KUNJUNGAN_DETAIL_FAILURE: GET_KUNJUNGAN_DETAIL[FAILURE],

  GET_KUNJUNGAN_UNIT_DETAIL_REQUEST: GET_KUNJUNGAN_UNIT_DETAIL[REQUEST],
  GET_KUNJUNGAN_UNIT_DETAIL_SUCCESS: GET_KUNJUNGAN_UNIT_DETAIL[SUCCESS],
  GET_KUNJUNGAN_UNIT_DETAIL_FAILURE: GET_KUNJUNGAN_UNIT_DETAIL[FAILURE],

  ADD: createType('ADD'),
  EDIT: createType('EDIT'),
  DELETE: createType('DELETE'),
  CANCEL: createType('CANCEL'),
  FINISH: createType('FINISH'),
  SELECTED: createType('SELECTED'),
  INPUT_CHANGE_IDENTITAS: createType('INPUT_CHANGE_IDENTITAS'),
  SUBMIT_FILTER: createType('SUBMIT_FILTER'),
  ON_FOCUS_ELEMENT: createType('ON_FOCUS_ELEMENT'),
  RESET_FILTER: createType('RESET_FILTER'),
  RESET: createType('RESET'),
  READY: createType('READY'),
  OPEN_FORM: createType('OPEN_FORM'),
  LOAD_ALL: createType('LOAD_DATA'),
  CHANGE_SELECT2: createType('CHANGE_SELECT2'),
  SELECTED_KUNJUNGAN: createType('SELECTED_KUNJUNGAN'),
  SHOW_CARI_KUNJUNGAN: createType('SHOW_CARI_KUNJUNGAN'),
  HIDE_CARI_KUNJUNGAN: createType('HIDE_CARI_KUNJUNGAN'),
  POPULATE_ADD: createType('POPULATE_ADD'),
  CANCEL_SELECTED_KUNJUNGAN: createType('CANCEL_SELECTED_KUNJUNGAN'),
  SHOW_CARI_TINDAKAN: createType('SHOW_CARI_TINDAKAN'),
  HIDE_CARI_TINDAKAN: createType('HIDE_CARI_TINDAKAN'),
  SELECTED_TINDAKAN_SUGGESTION: createType('SELECTED_TINDAKAN_SUGGESTION'),
  INPUT_CHANGE_SEARCH_TINDAKAN: createType('INPUT_CHANGE_SEARCH_TINDAKAN'),
  SUBMIT_FILTER_TINDAKAN_SUGGESTION: createType(
    'SUBMIT_FILTER_TINDAKAN_SUGGESTION'
  ),
  INPUT_CHANGE_KONSUL: createType('INPUT_CHANGE_KONSUL'),
};
