import { staticConst } from '../static';

export default {
  data: {
    kunjungan: [],
    unitLayanan: [],
    kelompok: [],
    instalasi: [],
    kelasKamar: [],
    administrasiKonsul: [],
  },
  kunjungan: {
    id_pasien: '',
    nama_pasien: '',
    nama_ortu: '',
    norm: '',
    alamat: '',
    jenis_kelamin: '',
    id_dpjp: '',
    id_unit_layanan: '',
    id_instalasi: '',
    nama_unit_layanan: '',
    nama_instalasi: '',
    id_kunjungan_unit: '',
    umur: '',
    tgl_lahir: '',
    st_pulang: '',
    id: '',
    nama_status_pasien: '',
    nama_hak_kelas: '',
    nama_kelas: '',
    id_kelas: '',
    nama_dpjp: '',
    id_penjamin: '',
    kode_kunjungan_unit: '',
    keringanan: 0,
    bayar: 0,
    pengembalian: 0,
    biaya: 0,
    total_biaya: 0,
    tgl_kunjungan: '',
    nama_asal_masuk: '',
    nama_penjamin: '',
    nama_kelompok: '',
    id_kelompok: '',
  },
  post: {
    id: '',
    id_kelas: staticConst.ID_NON_KELAS,
    id_kelompok: '',
    id_tindakan: '',
    id_unit_layanan: '',
    id_instalasi: '',
    tgl_mulai: '',
    jam_mulai: '',
    nama_kelas: staticConst.NON_KELAS,
  },
  selectedOption: {
    id_kelompok: null,
    id_unit_layanan: null,
    id_instalasi: null,
    id_tindakan: null,
  },
  focusElement: '',
  selectedRow: 0,
  statusForm: '',
  showCariKunjungan: false,
  saveSuccess: false,
  administrasiKonsulLoader: false,
};
