import {redux} from '@simrs/common';

const { types, createRequestType, createType} = redux;
const { REQUEST, SUCCESS, FAILURE } = types;
const GET_OPTIONS_KLASIFIKASI = createRequestType('GET_OPTIONS_KLASIFIKASI');
const GET_OPTIONS_VERSITARIF = createRequestType('GET_OPTIONS_VERSITARIF');

export default {
    GET_OPTIONS_KLASIFIKASI_REQUEST: GET_OPTIONS_KLASIFIKASI[REQUEST],
    GET_OPTIONS_KLASIFIKASI_SUCCESS: GET_OPTIONS_KLASIFIKASI[SUCCESS],
    GET_OPTIONS_KLASIFIKASI_FAILURE: GET_OPTIONS_KLASIFIKASI[FAILURE],

    GET_OPTIONS_VERSITARIF_REQUEST: GET_OPTIONS_VERSITARIF[REQUEST],
    GET_OPTIONS_VERSITARIF_SUCCESS: GET_OPTIONS_VERSITARIF[SUCCESS],
    GET_OPTIONS_VERSITARIF_FAILURE: GET_OPTIONS_VERSITARIF[FAILURE],

    CHANGE_KLASIFIKASI: createType('CHANGE_KLASIFIKASI'),
    CHANGE_VERSITARIF: createType('CHANGE_VERSITARIF'),
}