const staticConst = {
  TABLE_PERMINTAAN_PENUNJANG: 'TABLE_PERMINTAAN_PENUNJANG',
  TABLE_PENUNJANG: 'TABLE_PENUNJANG',
  PERMINTAAN: 'PERMINTAAN',
  DIPENUHI: 'DIPENUHI',
  DITOLAK: 'DITOLAK',
};

export { staticConst };
