const staticConst = {
  TABLE_PERMINTAAN_PENUNJANG: 'TABLE_PERMINTAAN_PENUNJANG',
  TABLE_CARI_TINDAKAN: 'TABLE_CARI_TINDAKAN',
  TABLE_PENUNJANG: 'TABLE_PENUNJANG',
  PERMINTAAN: 'PERMINTAAN',
  DIPENUHI: 'DIPENUHI',
  DITOLAK: 'DITOLAK',
  ID_PENJAMIN_UMUM: 0
};

export { staticConst };
