import { redux } from '@simrs/common';

const { types, createRequestType, createType } = redux;

const { REQUEST, SUCCESS, FAILURE } = types;
const POPULATE_FORM = createRequestType('POPULATE_FORM');
const POPULATE_FORM_SUMBERLAIN = createRequestType('POPULATE_FORM_SUMBERLAIN');
const POPULATE_FORM_FILTER = createRequestType('POPULATE_FORM_FILTER');
const LOAD_DATA_SUMBER = createRequestType('LOAD_DATA_SUMBER');
const PUSH_DATA_SUMBER = createRequestType('PUSH_DATA_SUMBER');
const PUSHALL_DATA_SUMBER = createRequestType('PUSHALL_DATA_SUMBER');
const REVERT_DATA_SETTING = createRequestType('REVERT_DATA_SETTING');
const REVERTALL_DATA_SETTING = createRequestType('REVERTALL_DATA_SETTING');
const LOAD_DATA_SETTING = createRequestType('LOAD_DATA_SETTING');

export const moduleActionTypes = {
    OPEN_FORM: createType('OPEN_FORM'),
    ON_FOCUS_ELEMENT: createType('ON_FOCUS_ELEMENT'),

    POPULATE_FORM_REQUEST: POPULATE_FORM[REQUEST],
    POPULATE_FORM_SUCCESS: POPULATE_FORM[SUCCESS],
    POPULATE_FORM_FAILURE: POPULATE_FORM[FAILURE],
}

export const sumberLainActionTypes = {
    POPULATE_FORM_SUMBERLAIN_REQUEST: POPULATE_FORM_SUMBERLAIN[REQUEST],
    POPULATE_FORM_SUMBERLAIN_SUCCESS: POPULATE_FORM_SUMBERLAIN[SUCCESS],
    POPULATE_FORM_SUMBERLAIN_FAILURE: POPULATE_FORM_SUMBERLAIN[FAILURE],

    CHANGE_SELECT2_SUMBERLAIN: createType('CHANGE_SELECT2_SUMBERLAIN'),
}

export const filterActionTypes = {
    POPULATE_FORM_FILTER_REQUEST: POPULATE_FORM_FILTER[REQUEST],
    POPULATE_FORM_FILTER_SUCCESS: POPULATE_FORM_FILTER[SUCCESS],
    POPULATE_FORM_FILTER_FAILURE: POPULATE_FORM_FILTER[FAILURE],

    CHANGE_SELECT2_FILTER: createType('CHANGE_SELECT2_FILTER'),
}

export const sumberActionTypes = {
    LOAD_DATA_SUMBER_REQUEST: LOAD_DATA_SUMBER[REQUEST],
    LOAD_DATA_SUMBER_SUCCESS: LOAD_DATA_SUMBER[SUCCESS],
    LOAD_DATA_SUMBER_FAILURE: LOAD_DATA_SUMBER[FAILURE],

    PUSH_DATA_SUMBER_REQUEST: PUSH_DATA_SUMBER[REQUEST],
    PUSH_DATA_SUMBER_SUCCESS: PUSH_DATA_SUMBER[SUCCESS],
    PUSH_DATA_SUMBER_FAILURE: PUSH_DATA_SUMBER[FAILURE],

    PUSHALL_DATA_SUMBER_REQUEST: PUSHALL_DATA_SUMBER[REQUEST],
    PUSHALL_DATA_SUMBER_SUCCESS: PUSHALL_DATA_SUMBER[SUCCESS],
    PUSHALL_DATA_SUMBER_FAILURE: PUSHALL_DATA_SUMBER[FAILURE],

    CHANGE_INPUT_SUMBER: createType('CHANGE_INPUT_SUMBER'),
    SEARCH_SUMBER: createType('SEARCH_SUMBER'),
    SELECTION_SUMBER_CHANGED: createType('SELECTION_SUMBER_CHANGED'),
}

export const settingActionTypes = {
    LOAD_DATA_SETTING_REQUEST: LOAD_DATA_SETTING[REQUEST],
    LOAD_DATA_SETTING_SUCCESS: LOAD_DATA_SETTING[SUCCESS],
    LOAD_DATA_SETTING_FAILURE: LOAD_DATA_SETTING[FAILURE],

    REVERT_DATA_SETTING_REQUEST: REVERT_DATA_SETTING[REQUEST],
    REVERT_DATA_SETTING_SUCCESS: REVERT_DATA_SETTING[SUCCESS],
    REVERT_DATA_SETTING_FAILURE: REVERT_DATA_SETTING[FAILURE],

    REVERTALL_DATA_SETTING_REQUEST: REVERTALL_DATA_SETTING[REQUEST],
    REVERTALL_DATA_SETTING_SUCCESS: REVERTALL_DATA_SETTING[SUCCESS],
    REVERTALL_DATA_SETTING_FAILURE: REVERTALL_DATA_SETTING[FAILURE],

    CHANGE_INPUT_SETTING: createType('CHANGE_INPUT_SETTING'),
    CHANGE_INPUT_DATA_SETTING: createType('CHANGE_INPUT_DATA_SETTING'),
    SEARCH_SETTING: createType('SEARCH_SETTING'),
    SELECTION_SETTING_CHANGED: createType('SELECTION_SETTING_CHANGED'),
}
