import 'xel/themes/cupertino.css';
import 'semantic-ui-css/semantic.min.css';
import 'ag-grid-community/dist/styles/ag-grid.css';
import 'ag-grid-community/dist/styles/ag-theme-balham.css';
import 'react-redux-toastr/lib/css/react-redux-toastr.min.css';
import 'react-datepicker/dist/react-datepicker.css';
// import '@simrs/main/src/static/css/semantic.min.css';
import '@simrs/main/src/static/css/menubar.css';
import '@simrs/main/src/static/css/grid.css';
import 'rc-tree/assets/index.css';
import '@simrs/billing/src/static/css/tailwindcss.css';
import './static/css/semantic-ui.css';
import './static/css/toastr.css';
