import { redux } from '@simrs/common';

const { types, createRequestType, createType } = redux;

const { REQUEST, SUCCESS, FAILURE } = types;
const POPULATE_FORM = createRequestType('POPULATE_FORM');
const POPULATE_FORM_UPLOADGAMBAR = createRequestType('POPULATE_FORM_UPLOADGAMBAR');
const CHANGE_STATUS_APLIKASI = createRequestType('CHANGE_STATUS_APLIKASI');
const AUTH_GET_GRANTED = createRequestType('AUTH_GET_GRANTED');
const SAVE_UPLOADGAMBAR = createRequestType('SAVE_UPLOADGAMBAR');
const DELETE_UPLOADGAMBAR = createRequestType('DELETE_UPLOADGAMBAR');
const GET_UPLOADGAMBAR_DETAIL = createRequestType('GET_UPLOADGAMBAR_DETAIL');

export default {
    POPULATE_FORM_REQUEST: POPULATE_FORM[REQUEST],
    POPULATE_FORM_SUCCESS: POPULATE_FORM[SUCCESS],
    POPULATE_FORM_FAILURE: POPULATE_FORM[FAILURE],

    AUTH_GET_GRANTED_REQUEST: AUTH_GET_GRANTED[REQUEST],
    AUTH_GET_GRANTED_SUCCESS: AUTH_GET_GRANTED[SUCCESS],
    AUTH_GET_GRANTED_FAILURE: AUTH_GET_GRANTED[FAILURE],

    CHANGE_STATUS_APLIKASI_REQUEST: CHANGE_STATUS_APLIKASI[REQUEST],
    CHANGE_STATUS_APLIKASI_SUCCESS: CHANGE_STATUS_APLIKASI[SUCCESS],
    CHANGE_STATUS_APLIKASI_FAILURE: CHANGE_STATUS_APLIKASI[FAILURE],

    POPULATE_FORM_UPLOADGAMBAR_REQUEST: POPULATE_FORM_UPLOADGAMBAR[REQUEST],
    POPULATE_FORM_UPLOADGAMBAR_SUCCESS: POPULATE_FORM_UPLOADGAMBAR[SUCCESS],
    POPULATE_FORM_UPLOADGAMBAR_FAILURE: POPULATE_FORM_UPLOADGAMBAR[FAILURE],

    GET_UPLOADGAMBAR_DETAIL_REQUEST: GET_UPLOADGAMBAR_DETAIL[REQUEST],
    GET_UPLOADGAMBAR_DETAIL_SUCCESS: GET_UPLOADGAMBAR_DETAIL[SUCCESS],
    GET_UPLOADGAMBAR_DETAIL_FAILURE: GET_UPLOADGAMBAR_DETAIL[FAILURE],

    SAVE_UPLOADGAMBAR_REQUEST:SAVE_UPLOADGAMBAR[REQUEST],
    SAVE_UPLOADGAMBAR_SUCCESS:SAVE_UPLOADGAMBAR[SUCCESS],
    SAVE_UPLOADGAMBAR_FAILURE:SAVE_UPLOADGAMBAR[FAILURE],

    DELETE_UPLOADGAMBAR_REQUEST: DELETE_UPLOADGAMBAR[REQUEST],
    DELETE_UPLOADGAMBAR_SUCCESS: DELETE_UPLOADGAMBAR[SUCCESS],
    DELETE_UPLOADGAMBAR_FAILURE: DELETE_UPLOADGAMBAR[FAILURE],

    CHANGE_SELECT2: createType('CHANGE_SELECT2'),
    CHANGE_PERSONEL: createType('CHANGE_PERSONEL'),
    CHANGE_JENISGAMBAR: createType('CHANGE_JENISGAMBAR'),
    CHANGE_IMAGE: createType('CHANGE_IMAGE'),
    CHANGE_GRUP: createType('CHANGE_GRUP'),
    OPEN_UPLOAD_GAMBAR: createType('OPEN_UPLOAD_GAMBAR'),
    CLOSE_UPLOAD_GAMBAR: createType('CLOSE_UPLOAD_GAMBAR'),
}

export const filterIndexActionTypes = {
    FILTER_CHANGE_STATUS_APLIKASI: createType('FILTER_CHANGE_STATUS_APLIKASI')
}
