import { redux } from '@simrs/common';

const { types, createRequestType, createType } = redux;

const { REQUEST, SUCCESS, FAILURE } = types;
const GET_OPTIONS_STATUSAKTIFKUNJUNGAN = createRequestType('GET_OPTIONS_STATUSAKTIFKUNJUNGAN');
const DUPLICATION = createRequestType('DUPLICATION');

export default {
    GET_OPTIONS_STATUSAKTIFKUNJUNGAN_REQUEST: GET_OPTIONS_STATUSAKTIFKUNJUNGAN[REQUEST],
    GET_OPTIONS_STATUSAKTIFKUNJUNGAN_SUCCESS: GET_OPTIONS_STATUSAKTIFKUNJUNGAN[SUCCESS],
    GET_OPTIONS_STATUSAKTIFKUNJUNGAN_FAILURE: GET_OPTIONS_STATUSAKTIFKUNJUNGAN[FAILURE],

    DUPLICATION_REQUEST: DUPLICATION[REQUEST],
    DUPLICATION_SUCCESS: DUPLICATION[SUCCESS],
    DUPLICATION_FAILURE: DUPLICATION[FAILURE],

    POPULATE_FORM: createType('POPULATE_FORM'),
    CHANGE_STATUSAKTIFKUNJUNGAN: createType('CHANGE_STATUSAKTIFKUNJUNGAN'),
    CHANGE_TANGGALAKTIF: createType('CHANGE_TANGGALAKTIF'),
    CHANGE_JAMAKTIF: createType('CHANGE_JAMAKTIF'),
    DUPLICATION: createType('DUPLICATION'),
    SELECTED_DUPLICATION: createType('SELECTED_DUPLICATION'),
    CANCEL_DUPLICATION: createType('CANCEL_DUPLICATION'),
    LOAD_DATA_ON_DUPLICATION: createType('LOAD_DATA_ON_DUPLICATION'),
}
