import { redux } from '@simrs/common';

const { types, createRequestType, createType } = redux;

const { REQUEST, SUCCESS, FAILURE } = types;
const GET_OPTIONS_JENISLAYANAN = createRequestType('GET_OPTIONS_JENISLAYANAN');
const GET_OPTIONS_KELOMPOKJENISLAYANAN = createRequestType('GET_OPTIONS_KELOMPOKJENISLAYANAN');

export default {
    GET_OPTIONS_JENISLAYANAN_REQUEST: GET_OPTIONS_JENISLAYANAN[REQUEST],
    GET_OPTIONS_JENISLAYANAN_SUCCESS: GET_OPTIONS_JENISLAYANAN[SUCCESS],
    GET_OPTIONS_JENISLAYANAN_FAILURE: GET_OPTIONS_JENISLAYANAN[FAILURE],

    GET_OPTIONS_KELOMPOKJENISLAYANAN_REQUEST: GET_OPTIONS_KELOMPOKJENISLAYANAN[REQUEST],
    GET_OPTIONS_KELOMPOKJENISLAYANAN_SUCCESS: GET_OPTIONS_KELOMPOKJENISLAYANAN[SUCCESS],
    GET_OPTIONS_KELOMPOKJENISLAYANAN_FAILURE: GET_OPTIONS_KELOMPOKJENISLAYANAN[FAILURE],

    POPULATE_FORM: createType('POPULATE_FORM'),
    CHANGE_SELECT2: createType('CHANGE_SELECT2'),
}
