import { redux } from '@simrs/common';

const { types, createRequestType, createType } = redux;
const { REQUEST, SUCCESS, FAILURE } = types;
const GET_OPTIONS_KELAS = createRequestType('GET_OPTIONS_KELAS');
const GET_KODEPANGGIL = createRequestType('GET_KODEPANGGIL');
const IMPORT_KELAS = createRequestType('IMPORT_KELAS');

export default {
    GET_OPTIONS_KELAS_REQUEST: GET_OPTIONS_KELAS[REQUEST],
    GET_OPTIONS_KELAS_SUCCESS: GET_OPTIONS_KELAS[SUCCESS],
    GET_OPTIONS_KELAS_FAILURE: GET_OPTIONS_KELAS[FAILURE],

    GET_KODEPANGGIL_REQUEST: GET_KODEPANGGIL[REQUEST],
    GET_KODEPANGGIL_SUCCESS: GET_KODEPANGGIL[SUCCESS],
    GET_KODEPANGGIL_FAILURE: GET_KODEPANGGIL[FAILURE],

    IMPORT_KELAS_REQUEST: IMPORT_KELAS[REQUEST],
    IMPORT_KELAS_SUCCESS: IMPORT_KELAS[SUCCESS],
    IMPORT_KELAS_FAILURE: IMPORT_KELAS[FAILURE],

    CHANGE_KELAS: createType('CHANGE_KELAS'),
    POPULATE_FORM: createType('POPULATE_FORM'),
    CHANGE_TANGGALAKTIF: createType('CHANGE_TANGGALAKTIF'),
    CHANGE_JAMAKTIF: createType('CHANGE_JAMAKTIF'),

    IMPORT_KELAS: createType('IMPORT_KELAS'),
    SELECTION_CHANGED_KELAS: createType('SELECTION_CHANGED_KELAS'),
    CANCEL_IMPORT_KELAS: createType('CANCEL_IMPORT_KELAS'),
    LOAD_DATA_ON_IMPORT_KELAS: createType('LOAD_DATA_ON_IMPORT_KELAS'),
    SHOW_BUTTON_IMPORT_KELAS: createType('SHOW_BUTTON_IMPORT_KELAS'),
    STATUS_NOT_BALANCE: createType('STATUS_NOT_BALANCE'),
}