import { redux } from '@simrs/common';

const { types, createRequestType, createType } = redux;

const { REQUEST, SUCCESS, FAILURE } = types;
const GET_PASIEN = createRequestType('GET_PASIEN');
const GET_RIWAYAT_KUNJUNGAN = createRequestType('GET_RIWAYAT_KUNJUNGAN');
const GET_RIWAYAT_KUNJUNGAN_UNIT = createRequestType(
  'GET_RIWAYAT_KUNJUNGAN_UNIT'
);
const GET_RIWAYAT_KUNJUNGAN_UNIT_DETAIL = createRequestType(
  'GET_RIWAYAT_KUNJUNGAN_UNIT_DETAIL'
);
const GET_KUNJUNGAN_DETAIL = createRequestType('GET_KUNJUNGAN_DETAIL');

export default {
  GET_PASIEN_REQUEST: GET_PASIEN[REQUEST],
  GET_PASIEN_SUCCESS: GET_PASIEN[SUCCESS],
  GET_PASIEN_FAILURE: GET_PASIEN[FAILURE],

  GET_RIWAYAT_KUNJUNGAN_REQUEST: GET_RIWAYAT_KUNJUNGAN[REQUEST],
  GET_RIWAYAT_KUNJUNGAN_UNIT_REQUEST: GET_RIWAYAT_KUNJUNGAN_UNIT[REQUEST],
  GET_RIWAYAT_KUNJUNGAN_UNIT_DETAIL_REQUEST:
    GET_RIWAYAT_KUNJUNGAN_UNIT_DETAIL[REQUEST],

  GET_KUNJUNGAN_DETAIL_REQUEST: GET_KUNJUNGAN_DETAIL[REQUEST],
  GET_KUNJUNGAN_DETAIL_SUCCESS: GET_KUNJUNGAN_DETAIL[SUCCESS],
  GET_KUNJUNGAN_DETAIL_FAILURE: GET_KUNJUNGAN_DETAIL[FAILURE],

  CANCEL: createType('CANCEL'),
  SELECTED: createType('SELECTED'),
  INPUT_CHANGE: createType('INPUT_CHANGE'),
  ON_FOCUS_ELEMENT: createType('ON_FOCUS_ELEMENT'),
  RESET: createType('RESET'),
  READY: createType('READY'),
  OPEN_FORM: createType('OPEN_FORM'),
  FINISH: createType('FINISH'),
  SELECTED_KUNJUNGAN: createType('SELECTED_KUNJUNGAN'),
  SELECTED_KUNJUNGAN_UNIT: createType('SELECTED_KUNJUNGAN_UNIT'),
};
