export default {
  data: {
    agama: [],
    pendidikan: [],
    pekerjaan: [],
    jenisKelamin: [],
    statusNikah: [],
    jenisUmur: [],
    kewarganegaraan: [],
    bahasaSehariHari: [],
  },
  post: {
    tgl_lahir: '',
    nama_panggilan: '',
    umur: '',
    jenis_umur: '',
    jenis_tgl_lahir: 'tgl_lahir_umur',
    nama: '',
    nama_ortu: '',
    nama_desa: '',
    nama_kecamatan: '',
    nama_kota: '',
    nama_provinsi: '',
    alamat: '',
    rt: '',
    rw: '',
    id_jenis_kelamin: '',
    nama_jenis_kelamin: '',
    norm: '',
    id_pasien: '',
    id_desa: '',
    id_kecamatan: '',
    id_kota: '',
    id_provinsi: '',
    id: '',
    id_agama: '',
    id_pendidikan: '',
    id_pekerjaan: '',
    id_status_nikah: '',
    id_kewarganegaraan: '',
    id_bahasa_sehari_hari: '',
    nilai_kepercayaan: '',
    no_ktp: '',
    nama_suami_istri: '',
  },
  selectedOption: {
    id_agama: null,
    id_pendidikan: null,
    id_pekerjaan: null,
    id_status_nikah: null,
    id_jenis_kelamin: null,
    id_kewarganegaraan: null,
    id_bahasa_sehari_hari: null,
    jenis_umur: null,
  },
  focusElement: '',
  statusForm: '',
  saveSuccess: false,
  filterWilayah: {
    show: false,
    post: {
      desa: '',
      kecamatan: '',
      kota: '',
      provinsi: '',
    },
    selected: {},
  },
};
