import { redux } from '@simrs/common';

const { types, createRequestType, createType } = redux;

const { REQUEST, SUCCESS, FAILURE } = types;
const GET_OPTIONS_PENANGGUNGJAWAB = createRequestType('GET_OPTIONS_PENANGGUNGJAWAB');

export default {
    GET_OPTIONS_PENANGGUNGJAWAB_REQUEST: GET_OPTIONS_PENANGGUNGJAWAB[REQUEST],
    GET_OPTIONS_PENANGGUNGJAWAB_SUCCESS: GET_OPTIONS_PENANGGUNGJAWAB[SUCCESS],
    GET_OPTIONS_PENANGGUNGJAWAB_FAILURE: GET_OPTIONS_PENANGGUNGJAWAB[FAILURE],

    POPULATE_FORM: createType('POPULATE_FORM'),
    CHANGE_PENANGGUNGJAWAB: createType('CHANGE_PENANGGUNGJAWAB'),
}
