import { redux } from '@simrs/common';

const { types, createRequestType, createType } = redux;

const { REQUEST, SUCCESS, FAILURE } = types;
const POPULATE_FORM = createRequestType('POPULATE_FORM');
const SAVE_SETTING_COUNTER = createRequestType('SAVE_SETTING_COUNTER');

export default {
    POPULATE_FORM_REQUEST: POPULATE_FORM[REQUEST],
    POPULATE_FORM_SUCCESS: POPULATE_FORM[SUCCESS],
    POPULATE_FORM_FAILURE: POPULATE_FORM[FAILURE],

    SAVE_SETTING_COUNTER_REQUEST: SAVE_SETTING_COUNTER[REQUEST],
    SAVE_SETTING_COUNTER_SUCCESS: SAVE_SETTING_COUNTER[SUCCESS],
    SAVE_SETTING_COUNTER_FAILURE: SAVE_SETTING_COUNTER[FAILURE],

    CHANGE_SELECT2: createType('CHANGE_SELECT2'),
    SETTING_COUNTER: createType('SETTING_COUNTER'),
    CANCEL_SETTING_COUNTER: createType('CANCEL_SETTING_COUNTER'),
    CHANGE_COUNTER: createType('CHANGE_COUNTER'),
}
