import { redux } from '@simrs/common';

const { types, createRequestType, createType } = redux;

const { REQUEST, SUCCESS, FAILURE } = types;
const GET_PASIEN = createRequestType('GET_PASIEN');
const POPULATE_FORM = createRequestType('POPULATE_FORM');
const SAVE = createRequestType('SAVE_DATA');
const GET_ALL_WILAYAH = createRequestType('GET_ALL_WILAYAH');

export default {
  SAVE_REQUEST: SAVE[REQUEST],
  SAVE_SUCCESS: SAVE[SUCCESS],
  SAVE_FAILURE: SAVE[FAILURE],

  POPULATE_FORM_REQUEST: POPULATE_FORM[REQUEST],
  POPULATE_FORM_SUCCESS: POPULATE_FORM[SUCCESS],
  POPULATE_FORM_FAILURE: POPULATE_FORM[FAILURE],

  GET_PASIEN_REQUEST: GET_PASIEN[REQUEST],
  GET_PASIEN_SUCCESS: GET_PASIEN[SUCCESS],
  GET_PASIEN_FAILURE: GET_PASIEN[FAILURE],

  GET_ALL_WILAYAH_REQUEST: GET_ALL_WILAYAH[REQUEST],

  EDIT: createType('EDIT'),
  CANCEL: createType('CANCEL'),
  SELECTED: createType('SELECTED'),
  INPUT_CHANGE: createType('INPUT_CHANGE'),
  ON_FOCUS_ELEMENT: createType('ON_FOCUS_ELEMENT'),
  RESET: createType('RESET'),
  READY: createType('READY'),
  OPEN_FORM: createType('OPEN_FORM'),
  CHANGE_SELECT2: createType('CHANGE_SELECT2'),
  FINISH: createType('FINISH'),
  TOGGLE_SHOW_CARI_WILAYAH: createType('TOGGLE_SHOW_CARI_WILAYAH'),
  FILTER_CHANGE_WILAYAH: createType('FILTER_CHANGE_WILAYAH'),
  FILTER_SUBMIT_WILAYAH: createType('FILTER_SUBMIT_WILAYAH'),
  FILTER_SELECTED_WILAYAH: createType('FILTER_SELECTED_WILAYAH'),
};
