import {redux} from '@simrs/common';

const { types, createRequestType, createType} = redux;
const { REQUEST, SUCCESS, FAILURE } = types;
const GET_OPTIONS_KLASIFIKASI = createRequestType('GET_OPTIONS_KLASIFIKASI');

export default {
    GET_OPTIONS_KLASIFIKASI_REQUEST: GET_OPTIONS_KLASIFIKASI[REQUEST],
    GET_OPTIONS_KLASIFIKASI_SUCCESS: GET_OPTIONS_KLASIFIKASI[SUCCESS],
    GET_OPTIONS_KLASIFIKASI_FAILURE: GET_OPTIONS_KLASIFIKASI[FAILURE],

    CHANGE_KLASIFIKASI: createType('CHANGE_KLASIFIKASI'),
}