import { redux } from '@simrs/common';

const { types, createRequestType, createType } = redux;
const { REQUEST, SUCCESS, FAILURE } = types;
const LOAD_ALL = createRequestType('LOAD_DATA');
const POPULATE_FORM = createRequestType('POPULATE_FORM');
const GET_OPTIONS_KELOMPOK = createRequestType('GET_OPTIONS_KELOMPOK');

export default {
    LOAD_ALL_REQUEST: LOAD_ALL[REQUEST],
    LOAD_ALL_SUCCESS: LOAD_ALL[SUCCESS],
    LOAD_ALL_FAILURE: LOAD_ALL[FAILURE],

    POPULATE_FORM_REQUEST: POPULATE_FORM[REQUEST],
    POPULATE_FORM_SUCCESS: POPULATE_FORM[SUCCESS],
    POPULATE_FORM_FAILURE: POPULATE_FORM[FAILURE],

    GET_OPTIONS_KELOMPOK_REQUEST: GET_OPTIONS_KELOMPOK[REQUEST],
    GET_OPTIONS_KELOMPOK_SUCCESS: GET_OPTIONS_KELOMPOK[SUCCESS],
    GET_OPTIONS_KELOMPOK_FAILURE: GET_OPTIONS_KELOMPOK[FAILURE],

    STATUS_NOT_BALANCE: createType('STATUS_NOT_BALANCE'),
    CHANGE_KLASIFIKASI: createType('CHANGE_KLASIFIKASI'),
    CHANGE_VERSITARIF: createType('CHANGE_VERSITARIF'),
    CHANGE_KELOMPOK: createType('CHANGE_KELOMPOK'),
    CHANGE_KELAS: createType('CHANGE_KELAS'),
    CHANGE_TARIF: createType('CHANGE_TARIF'),

    FILTER_SUBMIT_SUCCESS: createType('FILTER_SUBMIT_SUCCESS'),
    FILTER_SUBMIT_FAILURE: createType('FILTER_SUBMIT_FAILURE'),
    ON_FOCUS_ELEMENT: createType('ON_FOCUS_ELEMENT'),
}