const ScreeningIntervensiGiziLabel = {
  headerLabel: 'Intervensi Gizi',
  descriptionLabel: '',
  formLabel: [
    { index: 0, key: '', label: 'TB', satuan: 'cm' },
    { index: 1, key: '', label: 'TB', satuan: 'm' },
    { index: 2, key: '', label: 'TL', satuan: 'cm' },
    { index: 3, key: '', label: 'TB Est', satuan: 'cm' },
    { index: 4, key: '', label: 'TB Est', satuan: 'm' },
    { index: 5, key: '', label: 'BB Actual', satuan: '', inputSatuan: 'kg' },
    { index: 6, key: '', label: 'LLA', satuan: 'cm' },
    { index: 7, key: '', label: 'BB Ideal', satuan: 'kg' },
    { index: 8, key: '', label: 'BB (LLA)', satuan: 'kg' },
    { index: 9, key: '', label: 'BB / U', satuan: '' },
    { index: 10, key: '', label: 'BBR', satuan: '', inputSatuan: '%' },
    { index: 11, key: '', label: 'BMR', satuan: '', inputSatuan: 'kkl' },
    { index: 12, key: '', label: 'Status Gizi', satuan: '' },
    {
      index: 13,
      key: '',
      label: 'Total Energi',
      satuan: '',
      inputSatuan: 'kkl',
    },
    { index: 14, key: '', label: 'FA' },
    { index: 15, key: '', label: 'FS' },
    { index: 16, key: '', label: 'Protein' },
    { index: 17, key: '', label: 'Lemak' },
    { index: 18, key: '', label: 'Karbohidrat' },
    { index: 19, key: '', label: 'Diet' },
    { index: 20, key: '', label: 'Bentuk makanan' },
  ],
  statusGizi: [
    { key: 0, text: 'Underweight', value: 'Underweight' },
    { key: 1, text: 'Normal', value: 'Normal' },
    { key: 2, text: 'Overweight', value: 'Overweight' },
    { key: 3, text: 'Obese', value: 'Obese' },
  ],
  FA: [
    { key: 0, text: 'Pasien dengan ventilator', value: 0.95 },
    { key: 1, text: 'Pasien dengan bedrest', value: 1.05 },
    { key: 2, text: 'Mobilisasi hanya di tempat tidur', value: 1.1 },
    { key: 3, text: 'Pasien masih bisa berjalan di sekitar kamar', value: 1.2 },
    { key: 4, text: 'Aktifitas ringan', value: 1.3 },
    { key: 5, text: 'Aktifitas sedang', value: 1.4 },
    { key: 6, text: 'Aktifitas berat', value: 1.5 },
  ],
  FS: [
    { key: 0, text: 'Bedah minor', value: 1.1 },
    { key: 1, text: 'Bedah minor', value: 1.2 },
    { key: 2, text: 'Kenaikan suhu tubuh 1°C', value: 1.13 },
    { key: 3, text: 'Infeksi ringan hingga sedang', value: 1.2 },
    { key: 4, text: 'Infeksi ringan hingga sedang', value: 1.3 },
    { key: 5, text: 'Infeksi ringan hingga sedang', value: 1.4 },
    { key: 6, text: 'Pneumonia', value: 1.3 },
    { key: 7, text: 'Efusi pleura', value: 1.5 },
    { key: 8, text: 'PPOK', value: 1.5 },
    { key: 9, text: 'Asthma', value: 1.5 },
    { key: 10, text: 'Sepsis', value: 1.5 },
    { key: 11, text: 'Cancer', value: 1.5 },
    { key: 12, text: 'TB Paru', value: 1.6 },
    { key: 13, text: 'Emplyoma', value: 1.6 },
  ],
  diet: [
    { key: 0, text: 'Batu Ginjal', value: 'Batu Ginjal' },
    { key: 1, text: 'DM', value: 'DM' },
    { key: 2, text: 'Gagal Ginjal Kronik', value: 'Gagal Ginjal Kronik' },
    { key: 3, text: 'Hati', value: 'Hati' },
    { key: 4, text: 'Jantung', value: 'Jantung' },
    { key: 5, text: 'Kanker', value: 'Kanker' },
    { key: 6, text: 'Lambung', value: 'Lambung' },
    { key: 7, text: 'Rendah Garam', value: 'Rendah Garam' },
    { key: 8, text: 'Rendah Lemak', value: 'Rendah Lemak' },
    { key: 9, text: 'Rendah Kolesterol', value: 'Rendah Kolesterol' },
    { key: 10, text: 'Rendah Protein', value: 'Rendah Protein' },
    { key: 11, text: 'Rendah Purin', value: 'Rendah Purin' },
    { key: 12, text: 'Rendah Serat', value: 'Rendah Serat' },
    { key: 13, text: 'Stroke' },
    { key: 14, text: 'TETP', value: 'TETP' },
    { key: 15, text: 'TPRKh', value: 'TPRKh' },
  ],
  bentukMakanan: [
    { key: 0, text: 'Nasi', value: 'Nasi' },
    { key: 1, text: 'Nasi Tim', value: 'Nasi Tim' },
    { key: 2, text: 'Bubur Kasar', value: 'Bubur Kasar' },
    { key: 3, text: 'Bubur Halus', value: 'Bubur Halus' },
    { key: 4, text: 'Cair Oral', value: 'Cair Oral' },
    { key: 5, text: 'Cair Enteral', value: 'Cair Enteral' },
    { key: 6, text: 'Untuk Pasien Puasa', value: 'Untuk Pasien Puasa' },
  ],
};

export default ScreeningIntervensiGiziLabel;
