import { redux } from '@simrs/common';

const { types, createRequestType, createType } = redux;

const { REQUEST, SUCCESS, FAILURE } = types;
const GET_OPTIONS_JENISKLASIFIKASI = createRequestType('GET_OPTIONS_JENISKLASIFIKASI');

export default {
    GET_OPTIONS_JENISKLASIFIKASI_REQUEST: GET_OPTIONS_JENISKLASIFIKASI[REQUEST],
    GET_OPTIONS_JENISKLASIFIKASI_SUCCESS: GET_OPTIONS_JENISKLASIFIKASI[SUCCESS],
    GET_OPTIONS_JENISKLASIFIKASI_FAILURE: GET_OPTIONS_JENISKLASIFIKASI[FAILURE],

    POPULATE_FORM: createType('POPULATE_FORM'),
    CHANGE_JENISKLASIFIKASI: createType('CHANGE_JENISKLASIFIKASI'),
}
