import { redux } from '@simrs/common';

const { types, createRequestType, createType } = redux;

const { REQUEST, SUCCESS, FAILURE } = types;
const GET_OPTIONS_INSTALASI = createRequestType('GET_OPTIONS_INSTALASI');
const GET_OPTIONS_KATEGORI = createRequestType('GET_OPTIONS_KATEGORI');

export default {
    GET_OPTIONS_INSTALASI_REQUEST: GET_OPTIONS_INSTALASI[REQUEST],
    GET_OPTIONS_INSTALASI_SUCCESS: GET_OPTIONS_INSTALASI[SUCCESS],
    GET_OPTIONS_INSTALASI_FAILURE: GET_OPTIONS_INSTALASI[FAILURE],

    GET_OPTIONS_KATEGORI_REQUEST: GET_OPTIONS_KATEGORI[REQUEST],
    GET_OPTIONS_KATEGORI_SUCCESS: GET_OPTIONS_KATEGORI[SUCCESS],
    GET_OPTIONS_KATEGORI_FAILURE: GET_OPTIONS_KATEGORI[FAILURE],

    POPULATE_FORM: createType('POPULATE_FORM'),
    CHANGE_INSTALASI: createType('CHANGE_INSTALASI'),
    CHANGE_KATEGORI: createType('CHANGE_KATEGORI'),
}
