import { redux } from '@simrs/common';

const { types, createRequestType, createType } = redux;
const { REQUEST, SUCCESS, FAILURE } = types;
const SAVE = createRequestType('SAVE_DATA');
const POPULATE_FORM = createRequestType('POPULATE_FORM');
const ASAL_MASUK_DETAIL = createRequestType('ASAL_MASUK_DETAIL');
const INSTALASI = createRequestType('INSTALASI');
const UNIT_LAYANAN = createRequestType('UNIT_LAYANAN');
const OPTIONS_BY_UNITLAYANAN = createRequestType('OPTIONS_BY_UNITLAYANAN');
const JENIS_KLASIFIKASI_REGISTRASI = createRequestType('JENIS_KLASIFIKASI_REGISTRASI');
const GET_ALL_PASIEN = createRequestType('GET_ALL_PASIEN');
const GET_ALL_WILAYAH = createRequestType('GET_ALL_WILAYAH');

export default {
    SAVE_REQUEST: SAVE[REQUEST],
    SAVE_SUCCESS: SAVE[SUCCESS],
    SAVE_FAILURE: SAVE[FAILURE],

    POPULATE_FORM_REQUEST: POPULATE_FORM[REQUEST],
    POPULATE_FORM_SUCCESS: POPULATE_FORM[SUCCESS],
    POPULATE_FORM_FAILURE: POPULATE_FORM[FAILURE],

    ASAL_MASUK_DETAIL_REQUEST: ASAL_MASUK_DETAIL[REQUEST],
    ASAL_MASUK_DETAIL_SUCCESS: ASAL_MASUK_DETAIL[SUCCESS],
    ASAL_MASUK_DETAIL_FAILURE: ASAL_MASUK_DETAIL[FAILURE],

    GET_ALL_PASIEN_REQUEST: GET_ALL_PASIEN[REQUEST],
    GET_ALL_WILAYAH_REQUEST: GET_ALL_WILAYAH[REQUEST],
    
    INSTALASI_REQUEST: INSTALASI[REQUEST],
    INSTALASI_SUCCESS: INSTALASI[SUCCESS],
    INSTALASI_FAILURE: INSTALASI[FAILURE],

    UNIT_LAYANAN_REQUEST: UNIT_LAYANAN[REQUEST],
    UNIT_LAYANAN_SUCCESS: UNIT_LAYANAN[SUCCESS],
    UNIT_LAYANAN_FAILURE: UNIT_LAYANAN[FAILURE],

    OPTIONS_BY_UNITLAYANAN_REQUEST: OPTIONS_BY_UNITLAYANAN[REQUEST],
    OPTIONS_BY_UNITLAYANAN_SUCCESS: OPTIONS_BY_UNITLAYANAN[SUCCESS],
    OPTIONS_BY_UNITLAYANAN_FAILURE: OPTIONS_BY_UNITLAYANAN[FAILURE],

    JENIS_KLASIFIKASI_REGISTRASI_REQUEST: JENIS_KLASIFIKASI_REGISTRASI[REQUEST],
    JENIS_KLASIFIKASI_REGISTRASI_SUCCESS: JENIS_KLASIFIKASI_REGISTRASI[SUCCESS],
    JENIS_KLASIFIKASI_REGISTRASI_FAILURE: JENIS_KLASIFIKASI_REGISTRASI[FAILURE],

    RESET: createType('RESET'),
    ADD: createType('ADD'),
    EDIT: createType('EDIT'),
    DELETE: createType('DELETE'),
    SELECTED: createType('SELECTED'),
    ADD_WITH_SELECTED: createType('ADD_WITH_SELECTED'),
    CANCEL: createType('CANCEL'),
    FINISH: createType('FINISH'),
    CANCEL_WITH_SELECTED: createType('CANCEL_WITH_SELECTED'),
    READY: createType('READY'),
    OPEN_FORM: createType('OPEN_FORM'),
    CHANGE_INPUT: createType('CHANGE_INPUT'),
    ON_FOCUS_ELEMENT: createType('ON_FOCUS_ELEMENT'),
    CHANGE_SELECT2: createType('CHANGE_SELECT2'),

    TOGGLE_SHOW_CARI_PASIEN: createType('TOGGLE_SHOW_CARI_PASIEN'),
    TOGGLE_SHOW_CARI_WILAYAH: createType('TOGGLE_SHOW_CARI_WILAYAH'),
    TOGGLE_SHOW_CARI_KUNJUNGAN: createType('TOGGLE_SHOW_CARI_KUNJUNGAN'),

    FILTER_CHANGE_PASIEN: createType('FILTER_CHANGE_PASIEN'),
    FILTER_SUBMIT_PASIEN: createType('FILTER_SUBMIT_PASIEN'),
    FILTER_SELECTED_PASIEN: createType('FILTER_SELECTED_PASIEN'),

    FILTER_CHANGE_WILAYAH: createType('FILTER_CHANGE_WILAYAH'),
    FILTER_SUBMIT_WILAYAH: createType('FILTER_SUBMIT_WILAYAH'),
    FILTER_SELECTED_WILAYAH: createType('FILTER_SELECTED_WILAYAH'),

    FILTER_CHANGE_KUNJUNGAN: createType('FILTER_CHANGE_KUNJUNGAN'),
    FILTER_SUBMIT_KUNJUNGAN: createType('FILTER_SUBMIT_KUNJUNGAN'),
    FILTER_SELECTED_KUNJUNGAN: createType('FILTER_SELECTED_KUNJUNGAN'),
}