import { redux } from '@simrs/common';

const { types, createRequestType, createType } = redux;
const { REQUEST, SUCCESS, FAILURE } = types;
const SAVE = createRequestType('SAVE_DATA');
const POPULATE_FORM = createRequestType('POPULATE_FORM');
const ASAL_MASUK_DETAIL = createRequestType('ASAL_MASUK_DETAIL');
const INSTALASI = createRequestType('INSTALASI');
const UNIT_LAYANAN = createRequestType('UNIT_LAYANAN');
const OPTIONS_BY_UNITLAYANAN = createRequestType('OPTIONS_BY_UNITLAYANAN');
const GET_ALL_PASIEN = createRequestType('GET_ALL_PASIEN');
const GET_ALL_WILAYAH = createRequestType('GET_ALL_WILAYAH');
const NEXT_NORM = createRequestType('NEXT_NORM');
const GET_PASIEN = createRequestType('GET_PASIEN');
const GET_KUNJUNGAN_TERAKHIR = createRequestType('GET_KUNJUNGAN_TERAKHIR');
const GET_KUNJUNGAN_DETAIL = createRequestType('GET_KUNJUNGAN_DETAIL');
const GET_PENJAMIN_PASIEN = createRequestType('GET_PENJAMIN_PASIEN');

export default {
  SAVE_REQUEST: SAVE[REQUEST],
  SAVE_SUCCESS: SAVE[SUCCESS],
  SAVE_FAILURE: SAVE[FAILURE],

  POPULATE_FORM_REQUEST: POPULATE_FORM[REQUEST],
  POPULATE_FORM_SUCCESS: POPULATE_FORM[SUCCESS],
  POPULATE_FORM_FAILURE: POPULATE_FORM[FAILURE],

  ASAL_MASUK_DETAIL_REQUEST: ASAL_MASUK_DETAIL[REQUEST],
  ASAL_MASUK_DETAIL_SUCCESS: ASAL_MASUK_DETAIL[SUCCESS],
  ASAL_MASUK_DETAIL_FAILURE: ASAL_MASUK_DETAIL[FAILURE],

  GET_ALL_PASIEN_REQUEST: GET_ALL_PASIEN[REQUEST],
  GET_ALL_WILAYAH_REQUEST: GET_ALL_WILAYAH[REQUEST],

  INSTALASI_REQUEST: INSTALASI[REQUEST],
  INSTALASI_SUCCESS: INSTALASI[SUCCESS],
  INSTALASI_FAILURE: INSTALASI[FAILURE],

  UNIT_LAYANAN_REQUEST: UNIT_LAYANAN[REQUEST],
  UNIT_LAYANAN_SUCCESS: UNIT_LAYANAN[SUCCESS],
  UNIT_LAYANAN_FAILURE: UNIT_LAYANAN[FAILURE],

  OPTIONS_BY_UNITLAYANAN_REQUEST: OPTIONS_BY_UNITLAYANAN[REQUEST],
  OPTIONS_BY_UNITLAYANAN_SUCCESS: OPTIONS_BY_UNITLAYANAN[SUCCESS],
  OPTIONS_BY_UNITLAYANAN_FAILURE: OPTIONS_BY_UNITLAYANAN[FAILURE],

  NEXT_NORM_REQUEST: NEXT_NORM[REQUEST],
  NEXT_NORM_SUCCESS: NEXT_NORM[SUCCESS],
  NEXT_NORM_FAILURE: NEXT_NORM[FAILURE],

  GET_PASIEN_REQUEST: GET_PASIEN[REQUEST],
  GET_PASIEN_SUCCESS: GET_PASIEN[SUCCESS],
  GET_PASIEN_FAILURE: GET_PASIEN[FAILURE],

  GET_KUNJUNGAN_TERAKHIR_REQUEST: GET_KUNJUNGAN_TERAKHIR[REQUEST],
  GET_KUNJUNGAN_TERAKHIR_SUCCESS: GET_KUNJUNGAN_TERAKHIR[SUCCESS],
  GET_KUNJUNGAN_TERAKHIR_FAILURE: GET_KUNJUNGAN_TERAKHIR[FAILURE],

  GET_KUNJUNGAN_DETAIL_REQUEST: GET_KUNJUNGAN_DETAIL[REQUEST],
  GET_KUNJUNGAN_DETAIL_SUCCESS: GET_KUNJUNGAN_DETAIL[SUCCESS],
  GET_KUNJUNGAN_DETAIL_FAILURE: GET_KUNJUNGAN_DETAIL[FAILURE],

  GET_PENJAMIN_PASIEN_REQUEST: GET_PENJAMIN_PASIEN[REQUEST],
  GET_PENJAMIN_PASIEN_SUCCESS: GET_PENJAMIN_PASIEN[SUCCESS],
  GET_PENJAMIN_PASIEN_FAILURE: GET_PENJAMIN_PASIEN[FAILURE],

  RESET: createType('RESET'),
  ADD: createType('ADD'),
  EDIT: createType('EDIT'),
  DELETE: createType('DELETE'),
  SELECTED: createType('SELECTED'),
  ADD_WITH_SELECTED: createType('ADD_WITH_SELECTED'),
  CANCEL: createType('CANCEL'),
  FINISH: createType('FINISH'),
  CANCEL_WITH_SELECTED: createType('CANCEL_WITH_SELECTED'),
  READY: createType('READY'),
  OPEN_FORM: createType('OPEN_FORM'),
  CHANGE_INPUT: createType('CHANGE_INPUT'),
  ON_FOCUS_ELEMENT: createType('ON_FOCUS_ELEMENT'),
  CHANGE_SELECT2: createType('CHANGE_SELECT2'),

  TOGGLE_SHOW_CARI_PASIEN: createType('TOGGLE_SHOW_CARI_PASIEN'),
  TOGGLE_SHOW_CARI_WILAYAH: createType('TOGGLE_SHOW_CARI_WILAYAH'),
  TOGGLE_SHOW_CARI_KUNJUNGAN: createType('TOGGLE_SHOW_CARI_KUNJUNGAN'),
  TOGGLE_SHOW_NORM_MODAL: createType('TOGGLE_SHOW_NORM_MODAL'),

  FILTER_CHANGE_PASIEN: createType('FILTER_CHANGE_PASIEN'),
  FILTER_SUBMIT_PASIEN: createType('FILTER_SUBMIT_PASIEN'),
  FILTER_SELECTED_PASIEN: createType('FILTER_SELECTED_PASIEN'),

  FILTER_CHANGE_WILAYAH: createType('FILTER_CHANGE_WILAYAH'),
  FILTER_SUBMIT_WILAYAH: createType('FILTER_SUBMIT_WILAYAH'),
  FILTER_SELECTED_WILAYAH: createType('FILTER_SELECTED_WILAYAH'),

  FILTER_CHANGE_KUNJUNGAN: createType('FILTER_CHANGE_KUNJUNGAN'),
  FILTER_SUBMIT_KUNJUNGAN: createType('FILTER_SUBMIT_KUNJUNGAN'),
  FILTER_SELECTED_KUNJUNGAN: createType('FILTER_SELECTED_KUNJUNGAN'),
};
