export default {
    data: {
        options_jenis_kelamin: [],
        options_penjamin: [],
        options_kelas: [],
        options_status_kepersetaan: [],
        options_asal_masuk: [],
        options_asal_masuk_detail: [],
        options_status_pasien: [],
        options_penjamin_pasien: [],
        options_kelompok: [],
        options_instalasi: [],
        options_unit_layanan: [],
        options_kelas_kamar: [],
        options_asal_kunjungan: [],
        options_dpjp: [],
        options_karcis: [],
        options_pemeriksaan: [],
        options_administrasi_rm: [],
        options_umur: [],
    },
    post: {
        kode_kunjungan: '',
        tgl_kunjungan: '',
        id_penjamin_pasien: '',
        tgl_jaminan: '',
        tgl_selesai_jaminan: '',
        id_asal_masuk: '',
        id_asal_masuk_detail: '',
        tgl_lahir: '',
        umur: '',
        jenis_umur: '',
        id_dpjp: '',
        id_unit_layanan: '',
        id_kelas: '',
        tgl_mulai: '',
        id_kelompok: '',
        id_instalasi: '',
        jenis_tgl_lahir: 'tgl_lahir_umur',
        nama: '',
        nama_ortu: '',
        desa: '',
        kecamatan: '',
        kota: '',
        provinsi: '',
        alamat: '',
        rt: '',
        rw: '',
        jenis_kelamin_id: '',
        jenis_kelamin: '',
        norm: '',
        id_pasien: '',
        id_desa: '',
        id_kecamatan: '',
        id_kota: '',
        id_provinsi: '',
    },
    filterPasien: {
        post: {
            nama: '',
            desa: '',
            norm: '',
        },
        selected: {}
    },
    filterWilayah: {
        post: {
            desa: '',
            kecamatan: '',
            kota: '',
            provinsi: '',
        },
        selected: {}
    },
    selectedOption: {
        id_kelompok: null,
        id_instalasi: null,
        id_asal_masuk: null,
        id_asal_masuk_detail: null,
        id_jenis_kelamin: null,
        id_unit_layanan: null,
        id_kelas_kamar: null,
        id_dpjp: null,
        id_karcis: null,
        jenis_umur: null,
        
    },
    focusElement: '',
    statusForm: '',
    showCariPasien: false,
    showCariWilayah: false,
    showCariKunjungan: false,
    loaderAsalMasukDetail: false,
    loaderInstalasi: false,
    loaderUnitLayanan: false,
    loaderOptionsByUnitLayanan: false,
};