export default {
    data: {
        options_jenis_kelamin: [],
        options_penjamin: [],
        options_kelas: [],
        options_status_kepersetaan: [],
        options_asal_masuk: [],
        options_asal_masuk_detail: [],
        options_status_pasien: [],
        options_penjamin_pasien: [],
        options_kelompok: [],
        options_instalasi: [],
        options_unit_layanan: [],
        options_kelas_kamar: [],
        options_asal_kunjungan: [],
        options_dpjp: [],
        options_karcis: [],
        options_pemeriksaan: [],
        options_administrasi_rm: [],
        options_umur: [],
    },
    post: {
        asal_masuk: '',
        kelompok: '',
        instalasi: '',
        nama: '',
        desa: '',
        kecamatan: '',
        kota: '',
        provinsi: '',
        alamat: '',
        rt: '',
        rw: '',
        jenis_kelamin_id: '',
        jenis_kelamin: '',
        norm: '',
        pasien_id: '',
    },
    filterPasien: {
        post: {
            nama: '',
            desa: '',
            norm: '',
        },
        selected: {}
    },
    filterWilayah: {
        post: {
            desa: '',
            kecamatan: '',
            kota: '',
            provinsi: '',
        },
        selected: {}
    },
    selectedOption: {
        kelompok: null,
        instalasi: null,
    },
    focusElement: '',
    statusForm: '',
    showCariPasien: false,
    showCariWilayah: false,
    showCariKunjungan: false,
    loaderAsalMasukDetail: false,
    loaderInstalasi: false,
    loaderUnitLayanan: false,
    loaderKelasKamar: false,
};