import { redux } from '@simrs/common';

const { types, createRequestType, createType } = redux;
const { REQUEST, SUCCESS, FAILURE } = types;
const PEMESANAN_ITEM = createRequestType('LOAD_PEMESANAN_ITEM');
const PENERIMAAN = createRequestType('LOAD_PENERIMAAN');
const PENERIMAAN_ITEM = createRequestType('LOAD_PENERIMAAN_ITEM');

export default {
  PEMESANAN_ITEM_REQUEST: PEMESANAN_ITEM[REQUEST],
  PEMESANAN_ITEM_SUCCESS: PEMESANAN_ITEM[SUCCESS],
  PEMESANAN_ITEM_FAILURE: PEMESANAN_ITEM[FAILURE],

  PENERIMAAN_REQUEST: PENERIMAAN[REQUEST],
  PENERIMAAN_SUCCESS: PENERIMAAN[SUCCESS],
  PENERIMAAN_FAILURE: PENERIMAAN[FAILURE],

  PENERIMAAN_ITEM_REQUEST: PENERIMAAN_ITEM[REQUEST],
  PENERIMAAN_ITEM_SUCCESS: PENERIMAAN_ITEM[SUCCESS],
  PENERIMAAN_ITEM_FAILURE: PENERIMAAN_ITEM[FAILURE],

  SELECT_ITEM_PENERIMAAN: createType('SELECT_ITEM_PENERIMAAN'),
};
